"""Add is_suspended field to User model

Revision ID: 3069f77e301d
Revises: b64251b7a8c8
Create Date: 2024-08-08 10:57:36.886192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3069f77e301d'
down_revision = 'b64251b7a8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_suspended')

    # ### end Alembic commands ###
